# Generated by Django 5.0.1 on 2024-03-16 21:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(choices=[('admin', 'Administrador'), ('estandar', 'Estándar')], max_length=10, verbose_name='Tipo de rol')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Username', models.TextField(max_length=250)),
                ('Name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=200, verbose_name='Apellido')),
                ('citizenshipCard', models.IntegerField(verbose_name='Cedula de ciudadania')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.CharField(max_length=15)),
                ('roles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Tikest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=200, verbose_name='titulo')),
                ('Description', models.TextField(max_length=200, verbose_name='descripcion')),
                ('State', models.BooleanField(default=False)),
                ('Creation_Date', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=250, verbose_name='Accion')),
                ('Date', models.DateField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tikest')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user', verbose_name='Usuario')),
            ],
        ),
    ]
